//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ces_it.Properties.ViewRsx {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ces_it.Properties.ViewRsx.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ERROR]-[HomePage]-[Connection_Button_Click]-[CATCH] :.
        /// </summary>
        internal static string ErrorConnectionHomePage {
            get {
                return ResourceManager.GetString("ErrorConnectionHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ERROR]-[HomePage]-[Connection_Button_Click]-[ELSE]-[SWITCH/CASE] :.
        /// </summary>
        internal static string ErrorSwitchCaseConnection {
            get {
                return ResourceManager.GetString("ErrorSwitchCaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INTERFACE ADMIN.
        /// </summary>
        internal static string NameInterfaceAdmin {
            get {
                return ResourceManager.GetString("NameInterfaceAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INTERFACE CLIENT .
        /// </summary>
        internal static string NameInterfaceClient {
            get {
                return ResourceManager.GetString("NameInterfaceClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INTERFACE COMMERCIAL.
        /// </summary>
        internal static string NameInterfaceCommercial {
            get {
                return ResourceManager.GetString("NameInterfaceCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INTERFACE LIVREUR.
        /// </summary>
        internal static string NameInterfaceLivreur {
            get {
                return ResourceManager.GetString("NameInterfaceLivreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INTERFACE RESTAURATEUR.
        /// </summary>
        internal static string NameInterfaceRestaurateur {
            get {
                return ResourceManager.GetString("NameInterfaceRestaurateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADMIN CONNEXION.
        /// </summary>
        internal static string NameTypeAdminConnexion {
            get {
                return ResourceManager.GetString("NameTypeAdminConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [SUCCESS]-[HomePage]-[Connection_Button_Click]-[TRY]-[ADMIN_INTERFACE_OPEN] :.
        /// </summary>
        internal static string SucessHomePageConnectionAdminLog {
            get {
                return ResourceManager.GetString("SucessHomePageConnectionAdminLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [SUCCESS]-[HomePage]-[Connection_Button_Click]-[TRY]-[COMMERCIAL_INTERFACE_OPEN] :.
        /// </summary>
        internal static string SucessHomePageConnectionCommercialLog {
            get {
                return ResourceManager.GetString("SucessHomePageConnectionCommercialLog", resourceCulture);
            }
        }
    }
}
